### ISSUE TITLE
Incoherence between python file name and lambda handler

### ISSUE THREAD

**Issue by akalck** [iops-team/terraform-aws-lambda-rds-fargate-service-scheduler#1]
Lambda is not able to run due to this error : 
[ERROR] Runtime.ImportModuleError: Unable to import module 'lambda_function': No module named 'lambda_function'
Traceback (most recent call last)

As per the teraform code the handler name is "lambda_function.lambda_handler" but the python file name is not lambda_function but the name of the lambda function.

2 possibles solutions:

- change the lambda handler to "${var.lambda_function_name}.lambda_handler"
- force the python file name to lambda_function

**Comment by meks96** [comment]
@akalck Hello!
Thanks for the feedback!

The error occurs when using version 0.0.3?

**Comment by akalck** [comment]
Yes it is.
I solve it localy by setting the python file name to lambda_function

**Comment by meks96** [comment]
I already fixed this bug in version [0.0.4](https://github.com/iops-team/terraform-aws-lambda-rds-fargate-service-scheduler/releases/tag/0.0.4). Thanks again for your feedback!
